// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    FiltersPopup: typeof import('./src/components/Family/FiltersPopup.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    MonthBalance: typeof import('./src/components/Family/MonthBalance.vue')['default']
    MonthStats: typeof import('./src/components/Family/MonthStats.vue')['default']
    NailList: typeof import('./src/components/Piva/NailList.vue')['default']
    NewCategoryPopup: typeof import('./src/components/Family/NewCategoryPopup.vue')['default']
    NewNailPopup: typeof import('./src/components/Piva/NewNailPopup.vue')['default']
    NewTransactionPopup: typeof import('./src/components/Family/NewTransactionPopup.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Family/Settings.vue')['default']
    TagCategory: typeof import('./src/components/Family/TagCategory.vue')['default']
    TransactionList: typeof import('./src/components/Family/TransactionList.vue')['default']
    UpdateCategoryPopup: typeof import('./src/components/Family/UpdateCategoryPopup.vue')['default']
    UpdateNailPopup: typeof import('./src/components/Piva/UpdateNailPopup.vue')['default']
    UpdateTransactionPopup: typeof import('./src/components/Family/UpdateTransactionPopup.vue')['default']
  }
}
